import os
import random

import click

DIRECTORY = 'words'


@click.command()
@click.option('-h', '--handle', is_flag=False, flag_value=None,
              required=False, prompt_required=False,
              prompt='What word do you want to include in your username? (optional)')
@click.option('-l', '--length', type=int, default=2,
              show_default=True, prompt_required=False,
              prompt='How many words do you want your username to be?')
def cli(handle, length):
    if handle != None:
        hello(handle)
    get_username(length, handle)


def hello(handle):
    click.echo(f"hello {handle}!")


def get_username(length, handle):
    username = ''
    words = []
    for filename in os.listdir(DIRECTORY):
        f = os.path.join(DIRECTORY, filename)
        if os.path.isfile(f):
            words = words + get_words(f)

    random.shuffle(words)

    i = 0
    while i < length:
        ran_word = random.choice(words)
        if i == 0:
            username = ran_word
        else:
            username = username + f"_{ran_word}"
        i += 1

    if handle != None:
        username = f"{handle.lower()}_" + username

    click.echo(
        f"Your autogenerated username is: {click.style(username, fg='blue', bold=True)}")
    return username


def get_words(fpath):
    lines = []
    with open(fpath) as f:
        lines = [l.strip() for l in f.readlines()]
    return lines


if __name__ == '__main__':
    cli()
